// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpYJ40lM6vweV_IwOuVebQ2kkD4LLEHJk',
    appId: '1:402418398161:web:b06376250f66f5b873e6f0',
    messagingSenderId: '402418398161',
    projectId: 'safemind-7d84c',
    authDomain: 'safemind-7d84c.firebaseapp.com',
    storageBucket: 'safemind-7d84c.firebasestorage.app',
    measurementId: 'G-4SNSXRR8H9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo9EWIf9uo1kezPteCkvYbGH5U7j662eY',
    appId: '1:402418398161:android:a7f396e90dc58cd973e6f0',
    messagingSenderId: '402418398161',
    projectId: 'safemind-7d84c',
    storageBucket: 'safemind-7d84c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoPgyH0OkQXDE-9ZmklQi9JI3lSjB9_Aw',
    appId: '1:402418398161:ios:a1b11602537b167a73e6f0',
    messagingSenderId: '402418398161',
    projectId: 'safemind-7d84c',
    storageBucket: 'safemind-7d84c.firebasestorage.app',
    iosBundleId: 'com.example.safemind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoPgyH0OkQXDE-9ZmklQi9JI3lSjB9_Aw',
    appId: '1:402418398161:ios:a1b11602537b167a73e6f0',
    messagingSenderId: '402418398161',
    projectId: 'safemind-7d84c',
    storageBucket: 'safemind-7d84c.firebasestorage.app',
    iosBundleId: 'com.example.safemind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpYJ40lM6vweV_IwOuVebQ2kkD4LLEHJk',
    appId: '1:402418398161:web:d7be086fa80a4fb373e6f0',
    messagingSenderId: '402418398161',
    projectId: 'safemind-7d84c',
    authDomain: 'safemind-7d84c.firebaseapp.com',
    storageBucket: 'safemind-7d84c.firebasestorage.app',
    measurementId: 'G-GNN8NHS5PJ',
  );
}
